apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
spec:
  selector:
    matchLabels:
      app: core
  replicas: 1
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - name: core
        image: pholluxion/core:latest
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DATABASE
          value: "core"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "P4ssword!"
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app/data
          name: core-data
      volumes:
      - name: core-data
        persistentVolumeClaim:
          claimName: core-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: core
spec:
  type: NodePort
  selector:
    app: core
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080