apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-producer
spec:
  selector:
    matchLabels:
      app: payment-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-producer
    spec:
      containers:
      - name: payment-producer
        image: pholluxion/payment-producer:latest
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /app/data
          name: core-data
      volumes:
      - name: core-data
        persistentVolumeClaim:
          claimName: core-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: payment-producer
spec:
  type: NodePort
  selector:
    app: payment-producer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081