apiVersion: v1
kind: PersistentVolume
metadata:
  name: core-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/core-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
